# Local database service - commented out for Neon deployment
# services:
#   db:
#     image: postgres:16
#     container_name: tonetrace-db
#     env_file:
#       - .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data: